In [ ]:
import numpy as np

In [ ]:
arr=np.array([[1,2],[2,3]])

In [ ]:
arr.ndim

2

In [ ]:
arr.shape

(2, 2)

In [ ]:
range=np.arange(1,10,2) #start,stop,steps

In [ ]:
range

array([1, 3, 5, 7, 9])

In [ ]:
arr=np.linspace(0,1,10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
arr=np.logspace(1,3,3)
arr

array([  10.,  100., 1000.])

In [ ]:
arr=np.zeros([2,3]) #array full of zeros
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr=np.ones([2,3]) #array full of ones
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr=np.full([2,4],7) #It takes the paramaeres in the rows,columns, and the value
arr


array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [ ]:
arr2 = np.empty([2, 3])  # the uninitialized array
arr2


array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.random.rand(3) #this creater the random floatts

array([0.0387108 , 0.55704569, 0.61776328])

In [ ]:
arr=np.random.rand(2,3)# this creater the random [2,3] matrix
arr

array([[0.0693351 , 0.90478517, 0.40108531],
       [0.32606026, 0.37981636, 0.06256407]])

In [ ]:
np.random.randn()

-0.16804943110261528

In [ ]:
arr=np.random.randint(10,100,size=(2,3))
arr

array([[66, 61, 49],
       [37, 55, 88]])

# **Numpy Datatypes and type casting**

In [ ]:
arr=np.array([1,2,3,4,5,6])
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
lst=["String",45,45.65]
arr=np.array(lst)
arr

array(['String', '45', '45.65'], dtype='<U32')

In [ ]:
arr=np.array([1,2,3,4,5,5])
print(arr.dtype)
arr

int64


array([1, 2, 3, 4, 5, 5])

In [ ]:
arr=np.array([1,2,3,4,5,5],dtype=np.float64)
arr

array([1., 2., 3., 4., 5., 5.])

**TYPE CASTING**

In [ ]:
arr=np.array([1,2,3])
print(arr.dtype)
arr

int64


array([1, 2, 3])

In [ ]:
new_arr=arr.astype(np.float64)      #we cannot convert a string into integer or float
print(new_arr.dtype)
new_arr

float64


array([1., 2., 3.])

**create the multi dimensional array manually**

In [ ]:
arr=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.ndim

2

In [ ]:
arr.size

9

In [ ]:
arr.itemsize

8

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9])
reshaped=arr.reshape(3,3)
print(reshaped)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**Ravel**

In [ ]:
ravel=reshaped.ravel()

In [ ]:
#convert 1D array
ravel=reshaped.ravel()
ravel


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:

ravel[0]=100
print(ravel)
print(reshaped)

[100   2   3   4   5   6   7   8   9]
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


in the ravel array whichever changes which are done will reflect in the prg array


but when we perform the changes in the flatten array those changes will not be done in array

ARITHEMATIC OPRATION

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])


In [ ]:
print(a+b)

[5 7 9]


In [ ]:
print(a-b)

[-3 -3 -3]


In [ ]:
print(a*b)

[ 4 10 18]


In [ ]:
print(a/b)

[0.25 0.4  0.5 ]


In [ ]:
print(b//a)

[4 2 2]


In [ ]:
print(b%a)

[0 1 0]


In [ ]:
print(a^b)

[5 7 5]


In [ ]:
arr=np.array([1,4,9,16,25])

In [ ]:
print(np.sqrt(arr))

[1. 2. 3. 4. 5.]


In [ ]:
print(np.exp([1,2]))

[2.71828183 7.3890561 ]


In [ ]:
#sine function
angls=np.array([0,np.pi,np.pi/2])
print(np.sin(angls))

[0.0000000e+00 1.2246468e-16 1.0000000e+00]


In [ ]:
import numpy as np

In [ ]:
#indexing and slicing
arr=(1,4,9,16,25)
arr[-1:-4:-1]

(25, 16, 9)

In [ ]:
arr=np.array([1,2,3,4,5,6])
arr[: :2]

array([1, 3, 5])

In [ ]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
print(matrix[0:1,:])

[[1 2 3]]


In [ ]:
print(matrix[1: ,1: ])

[[5 6]
 [8 9]]


In [ ]:
arr=np.array([1,4,9,16,25])
ind=[2,4]

In [ ]:
#Iterating with nditer()
import numpy as np

In [ ]:
arr=np.array([[1,2],[3,4]])

In [ ]:
 for x in np.nditer(arr):
        print(x, end=" ")

1 2 3 4 

In [ ]:
# np.ndenumerate->both index+value

for ind,x in np.ndenumerate(arr):
    print(ind,x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [ ]:
#vieews vs copies
arr=np.array([1,2,3,4,5])
view =arr[1:3]
view

array([2, 3])

In [ ]:
view[0]=200
view

array([200,   3])

In [ ]:
#copy
copy=arr[1:3].copy()
copy

array([200,   3])

In [ ]:
copy[0]=2
copy

array([2, 3])

In [ ]:
arr

array([  1, 200,   3,   4,   5])

In [ ]:
#Transpose
arr=np.array([[1,2],[3,4]])
print(arr.transpose())

[[1 3]
 [2 4]]


In [ ]:
arr=np.array([[1,2],[3,4]])
arr.shape

(2, 2)

In [ ]:
swap=np.swapaxes(arr,0,1)
arr.shape

(2, 2)

In [ ]:
#concatenation
a=np.array([1,2])
b=np.array([6,7])


In [ ]:
combine=np.concatenate((a,b))
combine

array([1, 2, 6, 7])

In [ ]:
print(np.split(arr, 2))

[array([[1, 2]]), array([[3, 4]])]


In [ ]:
#Repeat function
arr=np.array([1,2,3,4])
print(np.repeat(arr,2))

[1 1 2 2 3 3 4 4]


In [ ]:
#tile
print(np.tile(arr,2))

[1 2 3 4 1 2 3 4]


In [ ]:
#aggregate function
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.sum(arr))

55


In [ ]:
#mean avg
print(np.mean(arr))

5.5


In [ ]:
#median
print(np.median(arr))


5.5


In [ ]:
np.std(arr)

np.float64(2.8722813232690143)

In [ ]:
np.var(arr)

np.float64(8.25)

In [ ]:
np.min(arr)

np.int64(1)

In [ ]:
np.max(arr)

np.int64(10)

In [ ]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.sum(matrix,axis=1)

array([ 6, 15, 24])

In [ ]:
#cumulative opration
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
print(np.cumsum(arr))

[ 1  3  6 10 15 21 28 36 45 55]


In [ ]:
print(np.cumprod(arr))

[      1       2       6      24     120     720    5040   40320  362880
 3628800]


Conditional bases choices


In [ ]:
#Where'
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
result=np.where(arr<5,"Low","High")
result

array(['Low', 'Low', 'Low', 'Low', 'High', 'High', 'High', 'High', 'High',
       'High'], dtype='<U4')

In [ ]:
arr1 = np.array([12,233,43,54,3])
print(np.argwhere(arr1>20))

[[1]
 [2]
 [3]]


In [ ]:
mask=np.logical_and(arr1>30 , arr1<200)
mask

array([False, False,  True,  True, False])

In [ ]:
matrix


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(np.argwhere(matrix>5))

[[1 2]
 [2 0]
 [2 1]
 [2 2]]


In [ ]:
#Advance conditions using logical and and or
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
mask=np.logical_and(arr>6 , arr<10)
arr[mask]

array([7, 8, 9])

In [ ]:
mask=np.logical_or(arr<4,arr>5)
arr[mask]

array([ 1,  2,  3,  6,  7,  8,  9, 10])

In [ ]:
#Broadcasting streching the size of smaller array by which it can match the bigger array
image=np.array([[100,200],[100,150]])
image

array([[100, 200],
       [100, 150]])

In [ ]:
brightness=image+50
brightness

array([[150, 250],
       [150, 200]])

In [ ]:
image.shape

(2, 2)

In [ ]:
#Vctorization

#np.vectorize()


In [ ]:
def square(x):
  return x*x
vfunc=np.vectorize(square)

In [ ]:
print(vfunc(arr))

[  1   4   9  16  25  36  49  64  81 100]


In [ ]:
#disadvantages slower then loop


In [ ]:
#dealing with missing values
a=np.array([12,12,3,23,24,24,np.nan,34,np.nan,34,np.nan])
a

array([12., 12.,  3., 23., 24., 24., nan, 34., nan, 34., nan])

In [ ]:
#np.inf and -np.inf -> positive and negative infinites


In [ ]:
a


array([12., 12.,  3., 23., 24., 24., nan, 34., nan, 34., nan])

In [ ]:
print(np.isnan(a))

[False False False False False False  True False  True False  True]


In [ ]:
b=np.array([1,np.nan,np.inf,10.2,40])
print(np.isinf(b))
print(np.isnan(b))
newb=np.nan_to_num(b)
newb

[False False  True False False]
[False  True False False False]


array([1.00000000e+000, 0.00000000e+000, 1.79769313e+308, 1.02000000e+001,
       4.00000000e+001])

In [ ]:
git init

SyntaxError: invalid syntax (2830201818.py, line 1)

In [188]:
get_ipython().system('git init')

Reinitialized existing Git repository in /content/.git/


In [189]:
get_ipython().system('git remote add origin git@github.com:sumitshinde2006/numpy.git')

error: remote origin already exists.


In [190]:
get_ipython().system('git branch -M main')

In [191]:
get_ipython().system('git push -u origin main')

error: src refspec main does not match any
error: failed to push some refs to 'github.com:sumitshinde2006/numpy.git'


In [192]:
get_ipython().system('git status')

On branch main

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.config/
	sample_data/

nothing added to commit but untracked files present (use "git add" to track)


In [193]:
get_ipython().system('git add .')

In [194]:
get_ipython().system('git commit -m "Initial commit of the notebook"')

Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@4c28f2698ac2.(none)')


In [195]:
get_ipython().system('git push -u origin main')

error: src refspec main does not match any
error: failed to push some refs to 'github.com:sumitshinde2006/numpy.git'


In [199]:
get_ipython().system('git config --global user.email "sumit.shinde_24uds@sanjivani.edu.in"')
get_ipython().system('git config --global user.name "sumitshinde2006"')

In [200]:
get_ipython().system('git commit -m "Initial commit of the notebook"')

On branch main
nothing to commit, working tree clean


In [201]:
get_ipython().system('git push -u origin main')

Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


In [204]:
get_ipython().system('ssh-keygen -t rsa -b 4096 -C "your_email@example.com" -f ~/.ssh/id_rsa -N ""')

Generating public/private rsa key pair.
/root/.ssh/id_rsa already exists.
Overwrite (y/n)? y
Your identification has been saved in /root/.ssh/id_rsa
Your public key has been saved in /root/.ssh/id_rsa.pub
The key fingerprint is:
SHA256:A0AeUTFGWa9Xl9Nx86AzyPwjlFcNuzi8LDxe5Sitd18 your_email@example.com
The key's randomart image is:
+---[RSA 4096]----+
|   .=+*+.     +=.|
|   . +.. + o o =*|
|    . .   B * = o|
|       . o = = o |
|        S o * o  |
|         + + B   |
|          = * . E|
|         . *. . .|
|          o. . ..|
+----[SHA256]-----+


In [205]:
get_ipython().system('cat ~/.ssh/id_rsa.pub')

ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCzJjJSZVs15c+u/hjeAX/NDjimyqAqsylw4qFQVF2Z5U5X/yr6e36larr1Yk+AbXBFqDUcDgQOVmvx/TTQeR1tvNJeM2fCeEuTe1RIEUNi52UTlEcxCqUm3sOuH2F2bj63Uz6IpAnAQ+qZgVhQ5Rdt8v4lPfVHHqBOosDww8y9IoYrmlexfVKeSJl5NV1Q5QJWg0sRzFsqmzRdpqd4TMfFjaPZtfHNSSXuCYaHzqc9C9KKgJMGBdvSiF5AVg4cE0AKMklFLcMgYAWWhmADIn/3MNRwe9RAORf+3MUNdwVKn3yTzOblgp4YR9YreIovlza057Exi6y991myo/8GAyCsEHLw9ZeozBgMWkOwcczlpLDg+54VTUFvLLDk+mgTT3rtdL3JtFclTbFyKSpXmWlD2vH6b4hjJcx0MH9wswbp5BM9B/H9dvyHdIgu9bXO9xAK7v7kEr7x066xkWeSFmhH4hmORw5hTg1FvYmA93bASsgjGa7V56TikUNjV52SueG4KRZuuKPSbiPOOgP5W0HsqC9gd972dsC9UQBLUDyUY6jb6EaI9yYYKR4QdmlWeLcai6HzUE4zBpK4VF7PkERSAnOZPU6Hn0XJYOVeMcjOr4k7d3W90gJU432WbTw89SMRhfFjuclm+aN4uM7qCVhjOjZMAOQf0aWdZO4J+ayX6w== your_email@example.com


In [206]:
get_ipython().system('eval "$(ssh-agent -s)"')

Agent pid 17888


In [207]:
get_ipython().system('ssh-add ~/.ssh/id_rsa')

Could not open a connection to your authentication agent.


Now, we need to configure SSH to accept GitHub's host key. This prevents the 'Host key verification failed' error.

In [208]:
get_ipython().system('mkdir -p ~/.ssh')
get_ipython().system('echo "Host github.com\n  StrictHostKeyChecking no\n  IdentityFile ~/.ssh/id_rsa\n  LogLevel ERROR" > ~/.ssh/config')

Now that the SSH agent is configured and GitHub's host key is accepted, let's try pushing your changes again.

In [209]:
get_ipython().system('git push -u origin main')

Enumerating objects: 28, done.
Counting objects: 100% (28/28), done.
Delta compression using up to 2 threads
Compressing objects: 100% (21/21), done.
Writing objects: 100% (28/28), 8.42 MiB | 2.47 MiB/s, done.
Total 28 (delta 5), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (5/5), done.
To github.com:sumitshinde2006/numpy.git
 * [new branch]      main -> main
Branch 'main' set up to track remote branch 'main' from 'origin'.
